name: Build rootless
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  make:
    name: Build Tweak
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install ldid and xz
        run: |
          brew install ldid xz
      - name: Setup Theos
        uses: actions/checkout@v2
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Download SDKs
        run: |
          curl -LO https://github.com/theos/sdks/archive/master.zip
          TMP=$(mktemp -d)
          unzip master.zip -d $TMP
          mv $TMP/sdks-master/*.sdk theos/sdks
          rm -r master.zip $TMP
      - name: Build Tweak
        id: build
        run: |
         make clean package FINALPACKAGE=1
         echo "::set-output name=package::$(ls -t packages | head -n1)"
      - name: Upload To GitHub Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          path: ./packages/*.deb
